.decl Arc(y:int32, x:int32)
.input Arc(IO="file", filename="Arc.csv", delimiter=",")

.decl Source(x:int32)
.input Source(IO="file", filename="Source.csv", delimiter=",")

.decl BipartiteViolation(x:int32)
.decl Zero(x:int32)
.decl One(x:int32)

Zero(x) :- Source(x).

One(y) :- Arc(x, y), Zero(x).
One(x) :- Arc(x, y), Zero(y).

Zero(y) :- Arc(x, y), One(x).
Zero(x) :- Arc(x, y), One(y).

BipartiteViolation(x) :- One(x), Zero(x).

.printsize BipartiteViolation
.printsize Zero
.printsize One
