#!/usr/bin/env python3
"""Compare FlowLog aggregate designs inside one executable.

All designs live in one binary, so code-layout effects mostly cancel. Each
sample runs every design of one cell back to back, in an order rotated per
sample; ratios are paired within a sample. Sample -1 is a discarded warmup.
"""

import argparse
import csv
import importlib.util
import json
import os
from pathlib import Path
import statistics
import subprocess


ROOT = Path(__file__).resolve().parents[1]
PROGRAM = ROOT / "programs/aggregate_designs/main.rs"
spec = importlib.util.spec_from_file_location("extrema", ROOT / "scripts/incremental_extrema.py")
extrema = importlib.util.module_from_spec(spec)
spec.loader.exec_module(extrema)

SHAPES = {
    "small": {"groups": 1_000_000, "values": 4, "duplicates": 1},
    "large": {"groups": 1_000, "values": 4_000, "duplicates": 1},
    "small-dup": {"groups": 250_000, "values": 4, "duplicates": 4},
    "large-dup": {"groups": 1_000, "values": 1_000, "duplicates": 4},
    # A global aggregate: routing by key sends every row to one worker.
    # Batch only; `--scale` multiplies its values instead of its groups.
    "global": {"groups": 1, "values": 4_000_000, "duplicates": 1},
    "global-dup": {"groups": 1, "values": 1_000_000, "duplicates": 4},
}
GLOBAL = {"global", "global-dup"}
DESIGNS = {
    ("batch", "extremum"): (
        "b-main", "b-weights", "b-weights-combine", "b-fused", "b-hash", "b-hash-combine",
        "b-hash-local", "b-hash-adaptive",
    ),
    ("batch", "additive"): (
        "b-main", "b-fused", "b-hash", "b-hash-combine", "b-dedup-hash", "b-dedup-local",
        "b-pair-local",
    ),
    ("incremental", "extremum"): (
        "i-runtime", "i-main", "i-scan", "i-endpoint", "i-hier", "i-custom", "i-lean",
    ),
    ("incremental", "additive"): (
        "i-runtime", "i-main", "i-scan", "i-weights", "i-custom", "i-lean",
    ),
}
BASELINES = {"batch": ("b-main", "b-weights"), "incremental": ("i-runtime", "i-scan")}
PHASES = ("winner-lat", "winner-thr", "interior-lat", "interior-thr", "support-lat", "support-thr")
FIELDS = [
    "shape", "family", "kind", "placement", "mode", "workers", "sample", "position",
    "load_s", *[f"{phase}_ms" for phase in PHASES], "peak_rss_kib", "checked_updates",
]


def designs(family, kind):
    return DESIGNS[(family, "extremum" if kind in ("min", "max") else "additive")]


def build(source, directory):
    directory.mkdir(parents=True, exist_ok=True)
    (directory / "Cargo.toml").write_text(
        '[package]\nname = "aggregate-designs"\nversion = "0.0.0"\nedition = "2024"\n'
        '[workspace]\n[dependencies]\n'
        f'flowlog-runtime = {{ path = {json.dumps(str(source / "flowlog-runtime"))} }}\n'
        'mimalloc = "0.1"\nrustc-hash = "2"\n'
        '[[bin]]\nname = "aggregate-designs"\n'
        f'path = {json.dumps(str(PROGRAM))}\n'
        # The profile and allocator of crates generated by flowlog-compiler.
        '[profile.release]\nopt-level = 2\npanic = "abort"\n'
    )
    if not (directory / "Cargo.lock").exists():
        subprocess.run(["cargo", "generate-lockfile", "--offline"], cwd=directory, check=True)
    environment = dict(os.environ)
    environment.pop("CARGO_TARGET_DIR", None)
    with (directory / "build.log").open("w") as log:
        result = subprocess.run(
            ["cargo", "build", "--release", "--locked", "--offline"],
            cwd=directory, env=environment, stdout=log, stderr=subprocess.STDOUT,
        )
    if result.returncode:
        raise RuntimeError(f"build failed:\n{(directory / 'build.log').read_text()}")
    return directory / "target/release/aggregate-designs"


def paired(rows, baseline, mode, metric):
    """Per-sample `baseline / mode` ratios; above 1 means `mode` is faster."""
    by_sample = {}
    for row in rows:
        if row["mode"] in (baseline, mode) and row[metric] is not None:
            by_sample.setdefault(row["sample"], {})[row["mode"]] = row[metric]
    ratios = [s[baseline] / s[mode] for s in by_sample.values() if baseline in s and mode in s]
    if not ratios:
        return None
    low, high = extrema.interval(ratios)
    return {"median": statistics.median(ratios), "ci95_low": low, "ci95_high": high}


def metrics_of(family):
    if family == "batch":
        return ["load_s"]
    return ["load_s", *[f"{phase}_ms" for phase in PHASES]]


def summarize(rows, cell, shape):
    family = cell["family"]
    measured = [
        row for row in rows
        if all(row[key] == value for key, value in cell.items()) and row["sample"] >= 0
    ]
    result = []
    for mode in designs(family, cell["kind"]):
        own = [row for row in measured if row["mode"] == mode]
        if not own:
            continue
        entry = {**cell, "mode": mode, "samples": len(own), **shape}
        entry["peak_rss_median_kib"] = statistics.median(row["peak_rss_kib"] for row in own)
        for metric in metrics_of(family):
            values = [row[metric] for row in own if row[metric] is not None]
            if not values:
                continue
            entry[f"{metric}_median"] = statistics.median(values)
            for baseline in BASELINES[family]:
                entry[f"{metric}_vs_{baseline}"] = paired(measured, baseline, mode, metric)
        result.append(entry)
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--build", type=Path, required=True)
    parser.add_argument("--output", type=Path)
    parser.add_argument("--build-only", action="store_true",
                        help="build the harness, print its path, and exit")
    parser.add_argument("--runs", type=int, default=3)
    parser.add_argument("--workers", type=int, default=1)
    parser.add_argument("--scale", type=int, default=1, help="multiply every shape's groups")
    parser.add_argument("--shapes", nargs="+", choices=SHAPES, default=list(SHAPES))
    parser.add_argument("--families", nargs="+", choices=("batch", "incremental"),
                        default=["batch", "incremental"])
    parser.add_argument("--kinds", nargs="+", choices=("min", "max", "sum", "count"),
                        default=["min", "max", "sum", "count"])
    parser.add_argument("--placements", nargs="+", choices=("local", "spread"),
                        default=["local", "spread"], help="batch placements")
    parser.add_argument("--modes", nargs="+", help="run only these designs")
    parser.add_argument("--warmup-rounds", type=int, default=2)
    parser.add_argument("--lat-touched", type=int, default=16)
    parser.add_argument("--lat-rounds", type=int, default=20)
    parser.add_argument("--thr-touched", type=int, default=16384, help="capped at groups / 4")
    parser.add_argument("--thr-rounds", type=int, default=6)
    args = parser.parse_args()
    if args.build_only:
        print(build(args.source.resolve(), args.build.resolve()))
        return
    if args.output is None:
        parser.error("--output is required unless --build-only is given")
    args.output.mkdir(parents=True, exist_ok=False)
    binary = build(args.source.resolve(), args.build.resolve())
    node, cpus = extrema.physical_cpus()
    if args.workers > len(cpus):
        raise RuntimeError(f"only {len(cpus)} physical CPUs on node {node}")
    pinned = ",".join(map(str, sorted(cpus)[-args.workers:]))
    rows, summary = [], []
    with (args.output / "attempts.csv").open("w", newline="") as file:
        writer = csv.DictWriter(file, fieldnames=FIELDS)
        writer.writeheader()
        for family in args.families:
            placements = args.placements if family == "batch" else ["spread"]
            for shape_name in args.shapes:
                if shape_name in GLOBAL and family != "batch":
                    continue
                scaled = "values" if shape_name in GLOBAL else "groups"
                shape = SHAPES[shape_name] | {scaled: SHAPES[shape_name][scaled] * args.scale}
                thr_touched = min(args.thr_touched, shape["groups"] // 4)
                phase_args = (
                    [0, 0, 0, 0, 0] if family == "batch" else [
                        args.warmup_rounds, args.lat_touched, args.lat_rounds,
                        thr_touched, args.thr_rounds,
                    ]
                )
                for kind in args.kinds:
                    for placement in placements:
                        cell = {
                            "shape": shape_name, "family": family, "kind": kind,
                            "placement": placement, "workers": args.workers,
                        }
                        modes = [m for m in designs(family, kind) if not args.modes or m in args.modes]
                        for sample in range(-1, args.runs):
                            shift = sample % len(modes)
                            for position, mode in enumerate(modes[shift:] + modes[:shift]):
                                stem = args.output / (
                                    f"{family}-{shape_name}-{kind}-{placement}-{mode}"
                                    f"-w{args.workers}-{sample}"
                                )
                                command = [
                                    "/usr/bin/time", "-f", "%M", "-o", f"{stem}.rss",
                                    "numactl", f"--physcpubind={pinned}", f"--membind={node}",
                                    str(binary), mode, kind, str(args.workers),
                                    str(shape["groups"]), str(shape["values"]),
                                    str(shape["duplicates"]), placement,
                                    *map(str, phase_args),
                                ]
                                result = subprocess.run(command, text=True, capture_output=True)
                                Path(f"{stem}.stdout").write_text(result.stdout)
                                Path(f"{stem}.stderr").write_text(result.stderr)
                                if result.returncode:
                                    raise RuntimeError(f"{' '.join(command)}\n{result.stderr}")
                                metrics = json.loads(result.stdout)
                                if not metrics["verified"]:
                                    raise RuntimeError(f"unverified output: {stem}")
                                row = {
                                    **cell, "mode": mode, "sample": sample,
                                    "position": position, "load_s": metrics["load_s"],
                                    "peak_rss_kib": int(Path(f"{stem}.rss").read_text()),
                                    "checked_updates": metrics["checked_updates"],
                                }
                                for phase in PHASES:
                                    timing = metrics["phases"].get(phase)
                                    row[f"{phase}_ms"] = (
                                        1000 * timing["seconds"] / timing["rounds"]
                                        if timing else None
                                    )
                                writer.writerow(row)
                                file.flush()
                                rows.append(row)
                        entries = summarize(rows, cell, shape)
                        summary.extend(entries)
                        cells = []
                        for entry in entries:
                            text = f"{entry['mode']}={entry['load_s_median']:.3f}s"
                            for phase in ("winner-lat", "winner-thr"):
                                key = f"{phase}_ms_median"
                                if key in entry:
                                    text += f"/{entry[key]:.2f}ms"
                            cells.append(text)
                        print(f"{family} {shape_name} {kind} {placement}: " + " ".join(cells),
                              flush=True)
    (args.output / "summary.json").write_text(json.dumps(summary, indent=2) + "\n")
    (args.output / "metadata.json").write_text(json.dumps({
        "source": extrema.source_info(args.source.resolve()),
        "binary": {"path": str(binary), "sha256": extrema.digest(binary)},
        "pinned_cpus": pinned,
        "numa_node": node,
        "parameters": {
            key: str(value) if isinstance(value, Path) else value
            for key, value in vars(args).items()
        },
        "all_outputs_verified": True,
    }, indent=2) + "\n")


if __name__ == "__main__":
    main()
